--- #YAML:1.0
name:               WWW-Orkut-API-Search
version:            0.2
abstract:           API for Orkut
author:
    - Daniel de Oliveira Mantovani <daniel.oliveira.mantovani@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    aliased:              0
    Carp:                 0
    HTML::TreeBuilder::XPath:  0
    Moose:                0
    Moose::Role:          0
    namespace::clean:     0
    Test::More:           0
    URI::Escape:          0
    URI::Query:           0
    WWW::Mechanize:       0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
